FROM ubuntu
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y gcc g++ libc-dev python3-dev python3-pip libxml2;
RUN pip install -r requirements.txt
EXPOSE 5000
CMD [ "python3" , "app.py" ]